### ISSUE TITLE
Silent stop server

### ISSUE THREAD

**Issue by Roman8x** [AantCoder/OnlineCity#15]
In the  weekend, when the number of users exceeds the usual, server silent crash.
Logs not contains Exception.

I suppose that, Some thread thread throw exception.
This is unhandled exception, try catch them

**Comment by Roman8x** [comment]
In pull request #26 I think resolve this: remove one increment count of users after connect.
But, need test for connections when user close game ALT+F4, variable _ActiveUserver not decremented, and when it summed to 1000 nobody will to connect. :-(

**Comment by Roman8x** [comment]
Also I add catch for  unhandled exceptions.

**Comment by AantCoder** [comment]
The problem seems to have been successfully fixed

Кажется проблема успешно устранена
