### ISSUE TITLE
Can there be an English version of Readme?

### ISSUE THREAD

**Issue by linonetwo** [AantCoder/OnlineCity#34]
That will attract more people to contribute.

Russian is great, it gave me a sense of communism. But as a Chinese, the only foreign language I can handle is English, sorry.

**Comment by AantCoder** [comment]
To translate readmy and comments you need to find a translator who would fulfill three conditions: knowledge of the Russian language, knowledge of the English language and knowledge of C # (and, preferably, a little knowledge of the project itself). Unlike regular text, highly specialized comments, even in their own language, can be difficult to understand. Unfortunately, I do not speak English and use a translator. :(

**Comment by linonetwo** [comment]
Okay...I think this is a great mod. Please keep going!
