### ISSUE TITLE
compiling

### ISSUE THREAD

**Issue by Marcus89uk** [AantCoder/OnlineCity#47]
how do i compile this?

**Comment by AantCoder** [comment]
If you have Steam, then specify the path to the Steam in the Source\Directory.Build.props file, in the <SteamFolder> tag. Required with a \ at the end.
Download and copy the Harmony and HugsLib mods to the Mods folder of the game.
Then create the OnlineCity folder there and copy all the files from the github of the project there (you don't need to copy the Source).
After that, the project will be compiled directly into the game folder.
The server is always compiled to the Source\RimWorldOnlineCityServerOut\netcoreapp3.1

Если у вас Steam, то укажите в файле Source\Directory.Build.props, в тэге <SteamFolder> путь до Steam. Обязательно с символом \ в конце.
Скачайте и скопируйте в папку Mods игры моды Harmony и HugsLib.
Потом создайте там папку OnlineCity и скопируйте туда все файлы с github проекта (можно не копировать Source).
Всё после этого проект будет компилироваться сразу в папку с игрой. 
Сервер всегда компилится в папку Source\RimWorldOnlineCityServerOut\netcoreapp3.1
