### ISSUE TITLE
Смерти колонистов без причин

### ISSUE THREAD

**Issue by Selengiks** [AantCoder/OnlineCity#82]
Кароч вот вся проблема. Гибнут колонисты без причин. Методом коллективного разума нашли проблемную строчку кода. Скриншоты проблемы и место проблемы прилагаются.

Когда игра пытается получить стат сознания, и если так повезет мод тоже в этот момент может эту фцию использовать из другого потока. Для пешки вернется сознание = 0% и она умрет

Мод используется на последней стабильной сборке HSK
Баг щамечен также на ванили, так что такие дела

![RimWorldWin64_fxR0jFJiUc](https://user-images.githubusercontent.com/38987970/113144231-b3a83780-9235-11eb-8476-daa7ad4e55e2.png)
![RimWorldWin64_5rbFjvNkWr](https://user-images.githubusercontent.com/38987970/113144240-b4d96480-9235-11eb-93eb-d643e74b2ae6.png)
![Discord_zlrQTuBUl8](https://user-images.githubusercontent.com/38987970/113144243-b571fb00-9235-11eb-9022-18429b873918.png)
![изображение_2021-03-31_152905](https://user-images.githubusercontent.com/38987970/113144367-d3d7f680-9235-11eb-9405-319e0e2f3478.png)

**Comment by AantCoder** [comment]
Наложил блокировку на этот метод, по идеи должно работать без сбоев!
