### ISSUE TITLE
OnlineCity server on Linux

### ISSUE THREAD

**Issue by bulbashenko** [AantCoder/OnlineCity#86]
Is it possible?

**Comment by Nathan-Moignard** [comment]
I am encountering an issue with the ServerClient-0.4.71a.
It seems to not include the DLL files required to work on linux (dotnet 3.1).
Moreover, when looking in included sources (OnlineCity-0.1.171.39), It seems that some sources are missing to recompile the project for Linux.

Is it possible to publish a new release with both Windows and Linux support ?

**Comment by AantCoder** [comment]
Unfortunately, we switched from NetCore to Framework. I don't understand Linux at all, try running it through Wine. Write if it works.

**Comment by PaintedCat** [comment]
>Write if it works.
К сожалению,это не работает. Сервер вроде запускается,но при попытке подключения римка зависает и потом вылетает подключение по тайм ауту. Сервак видит,что к нему попытались подключиться и видет вылет по тайм ауту.
